### ISSUE TITLE
使用InteractiveChat或MiaoChat替换Trchat

### ISSUE THREAD

**Issue by ZoruaFox** [ZoruaFox/ZoruaFox.github.io#1]
早先时期服务器玩家群曾曝出问题，反馈在玩家进入或退出服务器时会出现瞬卡。经过调查初步怀疑为聊天系统TrChat问题，具体表现在每当玩家进入或退出时向控制台抛出如下警告

```
[16:17:41 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[16:17:41 WARN]:        at TrChat-1.90-R5.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[16:17:41 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:17:41 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:17:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:17:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:17:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

正在调查该问题是否为Trchat引起，确定后进入项目。

**Comment by ZoruaFox** [comment]
之后选InteractiveChat吧，有点挑战性但还不至于。
